export const deltaForceGame = {
  id: "delta-force",
  name: "Delta Force",
  categoryId: "delta_force",

  note:
    "Región: Global\nRecarga de Delta Force. La moneda se entrega directamente a tu cuenta después de realizar el pedido.",

  playerField: {
    key: "player_id",
    label: "Player ID",
    type: "text",
  },

  offers: [
    {
      id: "18_delta_coins",
      name: "18 Delta Coins",
      display: "18🪙",
      price: 0.38,
      supplierPrice: 0.2217,
      icon: "🪙",
    },
    {
      id: "30_delta_coins",
      name: "30 Delta Coins",
      display: "30🪙",
      price: 0.54,
      supplierPrice: 0.3829,
      icon: "🪙",
    },
    {
      id: "60_delta_coins",
      name: "60 Delta Coins",
      display: "60🪙",
      price: 0.93,
      supplierPrice: 0.7758,
      icon: "🪙",
    },
    {
      id: "320_delta_coins",
      name: "320 Delta Coins",
      display: "320🪙",
      price: 4.04,
      supplierPrice: 3.8889,
      icon: "🪙",
    },
    {
      id: "460_delta_coins",
      name: "460 Delta Coins",
      display: "460🪙",
      price: 5.79,
      supplierPrice: 5.642,
      icon: "🪙",
    },
    {
      id: "750_delta_coins",
      name: "750 Delta Coins",
      display: "750🪙",
      price: 7.92,
      supplierPrice: 7.7678,
      icon: "🪙",
    },
    {
      id: "1480_delta_coins",
      name: "1480 Delta Coins",
      display: "1480🪙",
      price: 15.69,
      supplierPrice: 15.5357,
      icon: "🪙",
    },
    {
      id: "1980_delta_coins",
      name: "1980 Delta Coins",
      display: "1980🪙",
      price: 19.58,
      supplierPrice: 19.4246,
      icon: "🪙",
    },
    {
      id: "3950_delta_coins",
      name: "3950 Delta Coins",
      display: "3950🪙",
      price: 38.99,
      supplierPrice: 38.8391,
      icon: "🪙",
    },
    {
      id: "8100_delta_coins",
      name: "8100 Delta Coins",
      display: "8100🪙",
      price: 77.82,
      supplierPrice: 77.6682,
      icon: "🪙",
    },
    {
      id: "16200_delta_coins",
      name: "16200 Delta Coins",
      display: "16200🪙",
      price: 157.84,
      supplierPrice: 157.6929,
      icon: "🪙",
    },
    {
      id: "24300_delta_coins",
      name: "24300 Delta Coins",
      display: "24300🪙",
      price: 236.69,
      supplierPrice: 236.5449,
      icon: "🪙",
    },
    {
      id: "season_pass_operations_special",
      name: "Season Pass Operations Special",
      display: "PASE OPERACIONES 🎟️",
      price: 4.42,
      supplierPrice: 4.2647,
      icon: "🎟️",
    },
    {
      id: "season_pass_warfare_special",
      name: "Season Pass Warfare Special",
      display: "PASE WARFARE 🎟️",
      price: 4.42,
      supplierPrice: 4.2647,
      icon: "🎟️",
    },
    {
      id: "season_pass_delta_force_deluxe",
      name: "Season Pass Delta Force Deluxe",
      display: "DELUXE 🎟️",
      price: 6.06,
      supplierPrice: 5.909,
      icon: "🎟️",
    },
  ],
} as const;

export type DeltaForceOffer =
  (typeof deltaForceGame.offers)[number];
