export type FreeFireIdOffer = {
  id: string;
  name: string;
  displayName: string;
  supplierPrice: number;
  price: number;
  icon: string;
};

export const FREE_FIRE_ID = {
  categoryId: "free_fire_id",

  name: "Free Fire (ID)",

  image: "/images/free-fire-latam.jpg",

  note:
    "Región: Indonesia. Recarga de Free Fire. Ingrese su ID de jugador antes de realizar el pedido. Asegúrese de que su cuenta de Free Fire esté registrada en la región de Indonesia; los paquetes están bloqueados por región. El producto seleccionado se entrega directamente a su cuenta después de realizar el pedido.",

  field: {
    key: "player_id",
    label: "ID de jugador",
    type: "text",
  },

  offers: [
    {
      id: "5_diamonds",
      name: "5 Diamantes",
      displayName: "5💎",
      supplierPrice: 0.0504,
      price: 0.2504,
      icon: "💎",
    },
    {
      id: "12_diamonds",
      name: "12 Diamantes",
      displayName: "12💎",
      supplierPrice: 0.1008,
      price: 0.3008,
      icon: "💎",
    },
    {
      id: "10_diamonds",
      name: "10 Diamantes",
      displayName: "10💎",
      supplierPrice: 0.1128,
      price: 0.3128,
      icon: "💎",
    },
    {
      id: "20_diamonds",
      name: "20 Diamantes",
      displayName: "20💎",
      supplierPrice: 0.2156,
      price: 0.4156,
      icon: "💎",
    },
    {
      id: "25_diamantes",
      name: "25 Diamantes",
      displayName: "25💎",
      supplierPrice: 0.267,
      price: 0.467,
      icon: "💎",
    },
    {
      id: "level_up_pass_level_6",
      name: "Pase de subida de nivel - Nivel 6",
      displayName: "PASE NIVEL 6",
      supplierPrice: 0.2821,
      price: 0.4821,
      icon: "🎟️",
    },
    {
      id: "30_diamantes",
      name: "30 Diamantes",
      displayName: "30💎",
      supplierPrice: 0.3184,
      price: 0.5184,
      icon: "💎",
    },
    {
      id: "50_diamantes",
      name: "50 Diamantes",
      displayName: "50💎",
      supplierPrice: 0.4131,
      price: 0.6131,
      icon: "💎",
    },
    {
      id: "55_diamantes",
      name: "55 Diamantes",
      displayName: "55💎",
      supplierPrice: 0.4725,
      price: 0.6725,
      icon: "💎",
    },
    {
      id: "level_up_pass_level_20",
      name: "Pase de subida de nivel - Nivel 20",
      displayName: "PASE NIVEL 20",
      supplierPrice: 0.4735,
      price: 0.6735,
      icon: "🎟️",
    },
    {
      id: "level_up_pass_level_10",
      name: "Level Up Pass - Level 10",
      displayName: "PASE NIVEL 10",
      supplierPrice: 0.4735,
      price: 0.6735,
      icon: "🎟️",
    },
    {
      id: "level_up_pass_level_15",
      name: "Level Up Pass - Level 15",
      displayName: "PASE NIVEL 15",
      supplierPrice: 0.4735,
      price: 0.6735,
      icon: "🎟️",
    },
    {
      id: "level_up_pass_level_25",
      name: "Level Up Pass - Level 25",
      displayName: "PASE NIVEL 25",
      supplierPrice: 0.4735,
      price: 0.6735,
      icon: "🎟️",
    },
    {
      id: "70_diamonds",
      name: "70 Diamonds",
      displayName: "70💎",
      supplierPrice: 0.4836,
      price: 0.6836,
      icon: "💎",
    },
    {
      id: "80_diamonds",
      name: "80 Diamonds",
      displayName: "80💎",
      supplierPrice: 0.6367,
      price: 0.8367,
      icon: "💎",
    },
    {
      id: "level_up_pass_level_30",
      name: "Level Up Pass - Level 30",
      displayName: "PASE NIVEL 30",
      supplierPrice: 0.7556,
      price: 0.9556,
      icon: "🎟️",
    },
    {
      id: "100_diamonds",
      name: "100 Diamonds",
      displayName: "100💎",
      supplierPrice: 0.8534,
      price: 1.0534,
      icon: "💎",
    },
    {
      id: "120_diamonds",
      name: "120 Diamonds",
      displayName: "120💎",
      supplierPrice: 0.9561,
      price: 1.1561,
      icon: "💎",
    },
    {
      id: "140_diamantes",
      name: "140 Diamantes",
      displayName: "140💎",
      supplierPrice: 0.9974,
      price: 1.1974,
      icon: "💎",
    },
    {
      id: "130_diamantes",
      name: "130 Diamantes",
      displayName: "130💎",
      supplierPrice: 1.0589,
      price: 1.2589,
      icon: "💎",
    },
    {
      id: "145_diamantes",
      name: "145 Diamantes",
      displayName: "145💎",
      supplierPrice: 1.1203,
      price: 1.3203,
      icon: "💎",
    },
    {
      id: "150_diamantes",
      name: "150 Diamantes",
      displayName: "150💎",
      supplierPrice: 1.1717,
      price: 1.3717,
      icon: "💎",
    },
    {
      id: "190_diamantes",
      name: "190 Diamantes",
      displayName: "190💎",
      supplierPrice: 1.4901,
      price: 1.6901,
      icon: "💎",
    },
    {
      id: "210_diamantes",
      name: "210 Diamantes",
      displayName: "210💎",
      supplierPrice: 1.5929,
      price: 1.7929,
      icon: "💎",
    },
    {
      id: "200_diamantes",
      name: "200 Diamantes",
      displayName: "200💎",
      supplierPrice: 1.5929,
      price: 1.7929,
      icon: "💎",
    },
    {
      id: "membresía_semanal",
      name: "Membresía semanal",
      displayName: "MEMBRESÍA SEMANAL",
      supplierPrice: 1.4508,
      price: 1.6508,
      icon: "⭐",
    },
    {
      id: "280_diamantes",
      name: "280 Diamantes",
      displayName: "280💎",
      supplierPrice: 2.1268,
      price: 2.3268,
      icon: "💎",
    },
    {
      id: "tarjeta_bp",
      name: "Tarjeta BP",
      displayName: "TARJETA BP",
      supplierPrice: 2.3475,
      price: 2.5475,
      icon: "🎟️",
    },
    {
      id: "355_diamantes",
      name: "355 Diamantes",
      displayName: "355💎",
      supplierPrice: 2.418,
      price: 2.618,
      icon: "💎",
    },
    {
      id: "420_diamantes",
      name: "420 Diamantes",
      displayName: "420💎",
      supplierPrice: 3.1857,
      price: 3.3857,
      icon: "💎",
    },
    {
      id: "500_diamantes",
      name: "500 Diamantes",
      displayName: "500💎",
      supplierPrice: 3.7711,
      price: 3.9711,
      icon: "💎",
    },
    {
      id: "510_diamantes",
      name: "510 Diamantes",
      displayName: "510💎",
      supplierPrice: 3.8738,
      price: 4.0738,
      icon: "💎",
    },
    {
      id: "565_diamantes",
      name: "565 Diamantes",
      displayName: "565💎",
      supplierPrice: 4.2547,
      price: 4.4547,
      icon: "💎",
    },
    {
      id: "635_diamantes",
      name: "635 Diamantes",
      displayName: "635💎",
      supplierPrice: 4.7886,
      price: 4.9886,
      icon: "💎",
    },
    {
      id: "membresía_mensual",
      name: "Membresía mensual",
      displayName: "MEMBRESÍA MENSUAL",
      supplierPrice: 4.3625,
      price: 4.5625,
      icon: "⭐",
    },
    {
      id: "720_diamantes",
      name: "720 Diamantes",
      displayName: "720💎",
      supplierPrice: 4.8259,
      price: 5.0259,
      icon: "💎",
    },
    {
      id: "800_diamantes",
      name: "800 Diamantes",
      displayName: "800💎",
      supplierPrice: 5.9503,
      price: 6.1503,
      icon: "💎",
    },
    {
      id: "860_diamantes",
      name: "860 Diamantes",
      displayName: "860💎",
      supplierPrice: 6.3815,
      price: 6.5815,
      icon: "💎",
    },
    {
      id: "930_diamantes",
      name: "930 Diamantes",
      displayName: "930💎",
      supplierPrice: 6.9165,
      price: 7.1165,
      icon: "💎",
    },
    {
      id: "1000_diamantes",
      name: "1000 Diamantes",
      displayName: "1000💎",
      supplierPrice: 7.4404,
      price: 7.6404,
      icon: "💎",
    },
    {
      id: "1050_diamantes",
      name: "1050 Diamantes",
      displayName: "1050💎",
      supplierPrice: 7.8716,
      price: 8.0716,
      icon: "💎",
    },
    {
      id: "1075_diamantes",
      name: "1075 Diamantes",
      displayName: "1075💎",
      supplierPrice: 7.9744,
      price: 8.1744,
      icon: "💎",
    },
    {
      id: "1080_diamantes",
      name: "1080 Diamantes",
      displayName: "1080💎",
      supplierPrice: 8.0257,
      price: 8.2257,
      icon: "💎",
    },
    {
      id: "1450_diamantes",
      name: "1450 Diamantes",
      displayName: "1450💎",
      supplierPrice: 9.6619,
      price: 9.8619,
      icon: "💎",
    },
    {
      id: "2180_diamantes",
      name: "2180 Diamantes",
      displayName: "2180💎",
      supplierPrice: 14.4879,
      price: 14.6879,
      icon: "💎",
    },
    {
      id: "2200_diamantes",
      name: "2200 Diamantes",
      displayName: "2200💎",
      supplierPrice: 16.3709,
      price: 16.5709,
      icon: "💎",
    },
    {
      id: "3640_diamantes",
      name: "3640 Diamantes",
      displayName: "3640💎",
      supplierPrice: 24.1397,
      price: 24.3397,
      icon: "💎",
    },
    {
      id: "7290_diamantes",
      name: "7290 Diamantes",
      displayName: "7290💎",
      supplierPrice: 48.3802,
      price: 48.5802,
      icon: "💎",
    },
  ] satisfies FreeFireIdOffer[],
} as const;
